#
# Copyright 2023-2024 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

springIntegrationGemFireVersion=1.0.1
springDataGemFireVersion=1.1.8
springBootGemFireVersion=1.1.8
projectBuildSourceEncoding=UTF-8
gemfireDockerImage=gemfire/gemfire:9.15.14
dockerUserName=gemfire
version=1.0.0-build.9999

gemfireVersion=9.15.14

additionalMavenRepoURLs=
