#
# Copyright 2023-2024 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

springIntegrationGemFireVersion=1.0.2-build.85
springDataGemFireVersion=1.1.9-build.137
springBootGemFireVersion=1.1.9-build.125
projectBuildSourceEncoding=UTF-8
gemfireDockerImage=gemfire/gemfire:9.15.11
dockerUserName=gemfire
version=1.0.0-build.9999

gemfireVersion=9.15.15-build.1870

additionalMavenRepoURLs=gcs://gemfire-build-resources/maven/gemfire,gcs://spring-gemfire-build-resources/maven
