#
# Copyright 2023-2025 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

springIntegrationGemFireVersion=1.0.1
springDataGemFireVersion=1.1.9
springBootGemFireVersion=1.1.10
projectBuildSourceEncoding=UTF-8
gemfireDockerImage=gemfire/gemfire:9.15
dockerUserName=gemfire
version=1.0.2-build.9999
gemfireVersion=9.15.16
spring.gemfire.enable.private.repositories=true

additionalMavenRepoURLs=
